### ISSUE TITLE
Should check against View, not Fragment

### ISSUE THREAD

**Issue by jamesmontemagno** [NView/NView#2]
https://github.com/NView/NView/blob/master/NView.ViewHelpers.Android/ViewHelpers.Android.cs#L56

This could be problematic as there is a Fragment and a Support Fragment. We should really try to just check to see if it is a View or ViewGroup really that we can inflate into.

**Comment by praeclarum** [comment]
No opinion. Your obsession with supporting support does worry me though. If it's just a ViewGroup then the code will pick that up.

**Comment by jamesmontemagno** [comment]
Sooo I guess it is fine as we can document to just pass in the View of your fragment. Pretty straight forward. No one really uses just Fragment, everyone uses Support Fragment due to multiple reasons, which is a shame.
